# Generated by Django 5.0.3 on 2024-03-13 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
            },
        ),
        migrations.CreateModel(
            name='Barra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desBarra', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Barra',
                'verbose_name_plural': 'Barras',
            },
        ),
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCanal', models.CharField(max_length=50)),
                ('numeroCanal', models.IntegerField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canales',
            },
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=5)),
                ('descClasificacion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Clasificacion',
                'verbose_name_plural': 'Clasificaciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=50)),
                ('nivelEducativo', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Detalle Serie',
                'verbose_name_plural': 'Detalle Series',
            },
        ),
        migrations.CreateModel(
            name='TipoSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSerie', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo Serie',
                'verbose_name_plural': 'Tipo Series',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folioCinta', models.IntegerField()),
                ('programa', models.CharField(max_length=150)),
                ('codigoBarra', models.CharField(max_length=12)),
                ('videoTipo', models.CharField(max_length=5)),
                ('condicionTrans', models.CharField(blank=True, max_length=150, null=True)),
                ('fechaCalificacion', models.DateField()),
                ('tx', models.CharField(blank=True, max_length=5, null=True)),
                ('fechaMovimiento', models.DateTimeField(auto_now=True)),
                ('usuarioMovimiento', models.CharField(blank=True, max_length=20, null=True)),
                ('pasadas', models.CharField(blank=True, max_length=5, null=True)),
                ('serieInternoExterno', models.IntegerField(blank=True, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaModificacionVideoteca', models.DateTimeField(auto_now=True)),
                ('institucionProductora', models.CharField(blank=True, max_length=300, null=True)),
                ('productor', models.CharField(blank=True, max_length=60, null=True)),
                ('fechaUltimoMovimiento', models.DateTimeField()),
                ('usuarioUltimoMovimiento', models.CharField(blank=True, max_length=20, null=True)),
                ('statusFusion', models.BooleanField(default=False)),
                ('fechaVigencia', models.DateTimeField()),
                ('atributo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacionDGTVE.atributo')),
                ('canal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacionDGTVE.canal')),
                ('clasificacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacionDGTVE.clasificacion')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPrograma', models.DateField()),
                ('horaInicial', models.TimeField()),
                ('horaFinal', models.TimeField()),
                ('bloque', models.CharField(blank=True, max_length=20, null=True)),
                ('secuencia', models.CharField(blank=True, max_length=20, null=True)),
                ('observacionesTransmision', models.CharField(blank=True, max_length=150, null=True)),
                ('statusTransmision', models.IntegerField(blank=True, null=True)),
                ('observaTransmision', models.CharField(blank=True, max_length=150, null=True)),
                ('duracion', models.TimeField()),
                ('numEnvio', models.IntegerField(blank=True, null=True)),
                ('fechaEnvio', models.DateTimeField()),
                ('usuarioEnvio', models.CharField(blank=True, max_length=20, null=True)),
                ('reprogramado', models.IntegerField(blank=True, null=True)),
                ('colorHexadecimal', models.CharField(blank=True, max_length=7, null=True)),
                ('nomCanal', models.CharField(blank=True, max_length=50, null=True)),
                ('subtitulaje', models.BooleanField(default=False)),
                ('fechaEnterado', models.DateTimeField()),
                ('observacionAviso', models.CharField(max_length=150)),
                ('programacionEliminada', models.BooleanField(default=False)),
                ('programacionAPasos', models.BooleanField(default=False)),
                ('barra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacionDGTVE.barra')),
                ('canal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacionDGTVE.canal')),
                ('programa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacionDGTVE.programa')),
            ],
            options={
                'verbose_name': 'Programacion',
                'verbose_name_plural': 'Programaciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleProgramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoAcepta', models.CharField(max_length=50)),
                ('fechaAceptaEnvio', models.DateTimeField()),
                ('usuarioAceptaEnvio', models.CharField(blank=True, max_length=20, null=True)),
                ('obsRecepcionProgramacion', models.CharField(blank=True, max_length=150, null=True)),
                ('statusAceptaEnvio', models.BooleanField(default=False)),
                ('statusRevisado', models.BooleanField(default=False)),
                ('enterado', models.BooleanField(default=False)),
                ('programacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacionDGTVE.programacion')),
            ],
            options={
                'verbose_name': 'Detalle Programacion',
                'verbose_name_plural': 'Detalles Programacion',
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSerie', models.CharField(max_length=150)),
                ('sinopsis', models.CharField(blank=True, max_length=150, null=True)),
                ('anioProduccion', models.DateField()),
                ('duracion', models.TimeField()),
                ('formatoCinta', models.CharField(max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True)),
                ('detalleSerie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacionDGTVE.detalleserie')),
                ('tipoSerie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacionDGTVE.tiposerie')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.AddField(
            model_name='programa',
            name='serie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacionDGTVE.serie'),
        ),
    ]
